#!/system/bin/sh

if [ ! -e /data/.notfirstrun ]
then
    APKLIST=`ls /system/hundan/*.apk`
    for INFILES in $APKLIST
    do
      echo  setup package:$INFILES
      pm install -r $INFILES
    done

    APKLIST=`ls /sdcard/hundan/*.apk`
    for INFILES in $APKLIST
    do
      echo  setup package:$INFILES
      pm install -r $INFILES
    done
    busybox touch /data/.notfirstrun	
fi

exit
